name: tiktok-random-5-slots

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Forcer un post immédiat pour ce run"
        type: boolean
        default: false
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- RESTORE STATE (used.json cumulatif) ----
      - name: Restore USED state (latest)
        id: used-restore
        uses: actions/cache/restore@v4
        with:
          path: state/used.json
          key: used-v1-${{ github.run_id }}
          restore-keys: |
            used-v1-

      # ---- RESTORE SCHEDULE (du jour) ----
      - name: Restore TODAY schedule (latest today)
        id: sch-restore
        uses: actions/cache/restore@v4
        with:
          path: state/schedule.json
          key: schedule-v1-${{ github.run_id }}-${{ env.TODAY }}
          restore-keys: |
            schedule-v1-${{ env.TODAY }}
            schedule-v1-
        env:
          TODAY: ${{ steps.set-today.outputs.today }}

      # On calcule la date (YYYY-MM-DD) une fois pour le job
      - name: Set TODAY
        id: set-today
        run: echo "today=$(TZ=Europe/Paris date +%F)" >> $GITHUB_OUTPUT

      - name: Clone upstream uploader
        run: |
          rm -rf upstream
          git clone https://github.com/makiisthenes/TiktokAutoUploader upstream

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (patched)
        run: |
          python -m pip install --upgrade pip
          pip install "selenium>=4.20.0" undetected-chromedriver
          pip install -r upstream/requirements.txt --no-deps
          pip install google-api-python-client google-auth google-auth-oauthlib

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node deps for signature
        run: |
          cd upstream/tiktok_uploader/tiktok-signature
          npm i

      - name: Ensure signature path exists (symlink + fallback browser.js)
        shell: bash
        run: |
          set -e
          ln -s upstream/tiktok_uploader tiktok_uploader 2>/dev/null || true
          mkdir -p tiktok_uploader/tiktok-signature
          B64='Y29uc3QgU2lnbmVyID0gcmVxdWlyZSgnLi9pbmRleCcpOwpjb25zdCB1cmwgPSBwcm9jZXNzLmFyZ3ZbMl07CmNvbnN0IHVzZXJBZ2VudCA9IHByb2Nlc3MuYXJndlszXTsKCihhc3luYyBmdW5jdGlvbiBtYWluKCkgewogIHRyeSB7CiAgICBjb25zdCBzaWduZXIgPSBuZXcgU2lnbmVyKHVybCwgdXNlckFnZW50KTsKICAgIGF3YWl0IHNpZ25lci5pbml0KCk7CiAgICBjb25zdCBzaWduID0gYXdhaXQgc2lnbmVyLnNpZ24odXJsKTsKICAgIGNvbnN0IG5hdmlnYXRvciA9IGF3YWl0IHNpZ25lci5uYXZpZ2F0b3IoKTsKICAgIGNvbnN0IG91dHB1dCA9IEpTT04uc3RyaW5naWZ5KHsKICAgICAgc3RhdHVzOiAib2siLAogICAgICBkYXRhOiB7IC4uLnNpZ24sIG5hdmlnYXRvciB9CiAgICB9KTsKICAgIGNvbnNvbGUubG9nKG91dHB1dCk7CiAgICBhd2FpdCBzaWduZXIuY2xvc2UoKTsKICB9IGNhdGNoIChlcnIpIHsKICAgIGNvbnNvbGUuZXJyb3IoZXJyKTsKICAgIHByb2Nlc3MuZXhpdCgxKTsKICB9Cn0pKCk7Cg=='
          echo "$B64" | base64 -d > tiktok_uploader/tiktok-signature/browser.js

      - name: Build signature bundle if present
        run: |
          if [ -f upstream/tiktok_uploader/tiktok-signature/build.mjs ]; then
            node upstream/tiktok_uploader/tiktok-signature/build.mjs || true
          fi

      - name: Create config.txt for uploader (root + upstream)
        run: |
          echo 'COOKIES_DIR=./CookiesDir' > config.txt
          echo 'VIDEOS_DIR=./VideosDirPath' >> config.txt
          echo 'POST_PROCESSING_VIDEO_PATH=./VideosDirPath' >> config.txt
          echo 'IMAGEMAGICK_FONT=Arial' >> config.txt
          echo 'IMAGEMAGICK_FONT_SIZE=80' >> config.txt
          echo 'IMAGEMAGICK_TEXT_FOREGROUND_COLOR=white' >> config.txt
          echo 'IMAGEMAGICK_TEXT_BACKGROUND_COLOR=black' >> config.txt
          echo 'TMP_YOUTUBE_VIDEO_DIR=' >> config.txt
          echo 'LANG=en' >> config.txt
          echo 'TIKTOK_BASE_URL=https://www.tiktok.com/upload?lang=' >> config.txt
          echo 'IMAGEMAGICK_BINARY=' >> config.txt
          cp config.txt upstream/config.txt

      - name: Enable FORCE_POST when requested
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force == 'true' }}
        run: echo "FORCE_POST=1" >> $GITHUB_ENV

      - name: Run Drive runner
        env:
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          GDRIVE_FOLDER_IDS:  ${{ secrets.GDRIVE_FOLDER_IDS }}
          TIKTOK_USERNAME:    ${{ secrets.TIKTOK_USERNAME }}
          COOKIES_BASE64:     ${{ secrets.COOKIES_BASE64 }}
        run: |
          mkdir -p state
          python gdrive_runner.py

      # ---- SAVE STATE (used.json mis à jour) ----
      - name: Save USED state (rolling)
        if: always()
        uses: actions/cache/save@v4
        with:
          path: state/used.json
          key: used-v1-${{ github.run_id }}

      # ---- SAVE SCHEDULE (du jour, mis à jour) ----
      - name: Save TODAY schedule (rolling)
        if: always()
        uses: actions/cache/save@v4
        with:
          path: state/schedule.json
          key: schedule-v1-${{ github.run_id }}-${{ steps.set-today.outputs.today }}
