name: tiktok-random-5-slots
on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # Ton dépôt (gdrive_runner + state + workflow)

      # On récupère le projet original dans ./upstream
      - name: Clone upstream project
        run: git clone https://github.com/makiisthenes/TiktokAutoUploader upstream

      # Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python deps for upstream (patched)
        run: |
          pip install undetected-chromedriver
          pip install -r upstream/requirements.txt --no-deps
      - run: pip install google-api-python-client google-auth google-auth-oauthlib

      # Node (signature requise par le projet upstream)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install node deps for signature
        run: |
          cd upstream/tiktok_uploader/tiktok-signature
          npm i

      # Exécution : on force le post pour test immédiat
      - name: Run Drive runner
        env:
          FORCE_POST: "1"  # <-- Test immédiat
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          GDRIVE_FOLDER_IDS:  ${{ secrets.GDRIVE_FOLDER_IDS }}
          TIKTOK_USERNAME:    ${{ secrets.TIKTOK_USERNAME }}
          COOKIES_BASE64:     ${{ secrets.COOKIES_BASE64 }}
        run: python gdrive_runner.py

      # Commit des états si modifiés (dans TON dépôt)
      - name: Commit state if changed
        run: |
          # Supprimer les dossiers temporaires avant de vérifier l'état
          rm -rf CookiesDir upstream
          
          # Vérifier uniquement les changements dans state/
          if [[ -n "$(git status --porcelain state)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state/*.json
            git commit -m "update state/schedule"
            git push --force
          else
            echo "Aucun changement dans state/, rien à commit."
          fi
