name: tiktok-random-5-slots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # 8h Paris l'hiver

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner ton repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Cloner et installer le projet TikTokAutoUploader
      - name: Clone upstream uploader
        run: |
          rm -rf upstream
          git clone https://github.com/makiisthenes/TiktokAutoUploader upstream
          pip install -r upstream/requirements.txt

      # 4. Créer config.txt dans upstream
      - name: Create config.txt for uploader
        run: |
          echo "cookies_dir: ../CookiesDir" > upstream/config.txt
          echo "videos_dir: ../VideosDir" >> upstream/config.txt
          echo "headless: true" >> upstream/config.txt
          echo "no_watermark: false" >> upstream/config.txt

      # 5. Lancer ton bot
      - name: Run Drive runner
        env:
          FORCE_POST: "1"
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          GDRIVE_FOLDER_IDS:  ${{ secrets.GDRIVE_FOLDER_IDS }}
          TIKTOK_USERNAME:    ${{ secrets.TIKTOK_USERNAME }}
          COOKIES_BASE64:     ${{ secrets.COOKIES_BASE64 }}
        run: |
          python gdrive_runner.py
