name: tiktok-random-5-slots

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Forcer un post immédiat pour ce run"
        type: boolean
        default: false
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone upstream uploader
        run: |
          rm -rf upstream
          git clone https://github.com/makiisthenes/TiktokAutoUploader upstream

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (patched)
        run: |
          python -m pip install --upgrade pip
          # corrige le conflit selenium/undetected-chromedriver
          pip install "selenium>=4.20.0" undetected-chromedriver
          # installe le reste sans résolution des deps
          pip install -r upstream/requirements.txt --no-deps
          # Google Drive
          pip install google-api-python-client google-auth google-auth-oauthlib

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node deps for signature
        run: |
          cd upstream/tiktok_uploader/tiktok-signature
          npm i

      # chemin attendu + browser.js de secours (base64) — pas de heredoc
      - name: Ensure signature path exists (symlink + fallback browser.js)
        shell: bash
        run: |
          set -e
          ln -s upstream/tiktok_uploader tiktok_uploader 2>/dev/null || true
          mkdir -p tiktok_uploader/tiktok-signature
          B64='Y29uc3QgU2lnbmVyID0gcmVxdWlyZSgnLi9pbmRleCcpOwpjb25zdCB1cmwgPSBwcm9jZXNzLmFyZ3ZbMl07CmNvbnN0IHVzZXJBZ2VudCA9IHByb2Nlc3MuYXJndlszXTsKCihhc3luYyBmdW5jdGlvbiBtYWluKCkgewogIHRyeSB7CiAgICBjb25zdCBzaWduZXIgPSBuZXcgU2lnbmVyKHVybCwgdXNlckFnZW50KTsKICAgIGF3YWl0IHNpZ25lci5pbml0KCk7CiAgICBjb25zdCBzaWduID0gYXdhaXQgc2lnbmVyLnNpZ24odXJsKTsKICAgIGNvbnN0IG5hdmlnYXRvciA9IGF3YWl0IHNpZ25lci5uYXZpZ2F0b3IoKTsKICAgIGNvbnN0IG91dHB1dCA9IEpTT04uc3RyaW5naWZ5KHsKICAgICAgc3RhdHVzOiAib2siLAogICAgICBkYXRhOiB7IC4uLnNpZ24sIG5hdmlnYXRvciB9CiAgICB9KTsKICAgIGNvbnNvbGUubG9nKG91dHB1dCk7CiAgICBhd2FpdCBzaWduZXIuY2xvc2UoKTsKICB9IGNhdGNoIChlcnIpIHsKICAgIGNvbnNvbGUuZXJyb3IoZXJyKTsKICAgIHByb2Nlc3MuZXhpdCgxKTsKICB9Cn0pKCk7Cg=='
          echo "$B64" | base64 -d > tiktok_uploader/tiktok-signature/browser.js

      - name: Build signature bundle if present
        run: |
          if [ -f upstream/tiktok_uploader/tiktok-signature/build.mjs ]; then
            node upstream/tiktok_uploader/tiktok-signature/build.mjs || true
          fi

      - name: Create config.txt for uploader (root + upstream)
        run: |
          echo 'COOKIES_DIR=./CookiesDir' > config.txt
          echo 'VIDEOS_DIR=./VideosDirPath' >> config.txt
          echo 'POST_PROCESSING_VIDEO_PATH=./VideosDirPath' >> config.txt
          echo 'IMAGEMAGICK_FONT=Arial' >> config.txt
          echo 'IMAGEMAGICK_FONT_SIZE=80' >> config.txt
          echo 'IMAGEMAGICK_TEXT_FOREGROUND_COLOR=white' >> config.txt
          echo 'IMAGEMAGICK_TEXT_BACKGROUND_COLOR=black' >> config.txt
          echo 'TMP_YOUTUBE_VIDEO_DIR=' >> config.txt
          echo 'LANG=en' >> config.txt
          echo 'TIKTOK_BASE_URL=https://www.tiktok.com/upload?lang=' >> config.txt
          echo 'IMAGEMAGICK_BINARY=' >> config.txt
          cp config.txt upstream/config.txt

      - name: Enable FORCE_POST when requested
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force == 'true' }}
        run: echo "FORCE_POST=1" >> $GITHUB_ENV

      - name: Run Drive runner
        env:
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          GDRIVE_FOLDER_IDS:  ${{ secrets.GDRIVE_FOLDER_IDS }}
          TIKTOK_USERNAME:    ${{ secrets.TIKTOK_USERNAME }}
          COOKIES_BASE64:     ${{ secrets.COOKIES_BASE64 }}
        run: python gdrive_runner.py

      - name: Commit state if changed
        run: |
          rm -rf CookiesDir upstream
          if [[ -n "$(git status --porcelain state)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state/*.json
            git commit -m "update state/schedule"
            git push --force
          else
            echo "Aucun changement dans state/, rien à commit."
          fi
