name: tiktok-random-5-slots

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # tests (tu remettras ton planning ensuite)

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      # 1) Ton dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Clone du projet upstream
      - name: Clone upstream uploader
        run: |
          rm -rf upstream
          git clone https://github.com/makiisthenes/TiktokAutoUploader upstream

      # 3) Python + deps (patch pour le conflit selenium)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (patched)
        run: |
          python -m pip install --upgrade pip
          # Résout le conflit selenium
          pip install "selenium>=4.20.0" undetected-chromedriver
          # Installe le reste sans résoudre les deps
          pip install -r upstream/requirements.txt --no-deps
          # Déps Google Drive
          pip install google-api-python-client google-auth google-auth-oauthlib

      # 4) Node (signature TikTok du projet)
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node deps for signature
        run: |
          cd upstream/tiktok_uploader/tiktok-signature
          npm i

      # 5) Créer config.txt aux DEUX endroits (racine et upstream)
      - name: Create config.txt for uploader (root + upstream)
        run: |
          # config utilisé si le CWD est la racine (ce qui est le cas quand on lance upstream/cli.py)
          echo "cookies_dir: ./CookiesDir" > config.txt
          echo "videos_dir: ./VideosDir" >> config.txt
          echo "headless: true" >> config.txt
          echo "no_watermark: false" >> config.txt

          # copie dans upstream/ au cas où le CWD serait upstream/
          cp config.txt upstream/config.txt

      # 6) Lancer ton runner (FORCE_POST pour tester tout de suite)
      - name: Run Drive runner
        env:
          FORCE_POST: "1"
          GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
          GDRIVE_FOLDER_IDS:  ${{ secrets.GDRIVE_FOLDER_IDS }}
          TIKTOK_USERNAME:    ${{ secrets.TIKTOK_USERNAME }}
          COOKIES_BASE64:     ${{ secrets.COOKIES_BASE64 }}
        run: python gdrive_runner.py

      # 7) Commit de l'état (ignore dossiers temporaires)
      - name: Commit state if changed
        run: |
          rm -rf CookiesDir upstream
          if [[ -n "$(git status --porcelain state)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state/*.json
            git commit -m "update state/schedule"
            git push --force
          else
            echo "Aucun changement dans state/, rien à commit."
          fi
